backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "New Page" # Used in the UI
    folder: "docs/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Zerynth_in_a_nutshell"
        name: "Zerynth_in_a_nutshell"
        file: "docs/intro/index.md"
        preview_path: "docs/intro/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Zerynth_components"
        name: "Zerynth_components"
        file: "docs/intro/components.md"
        preview_path: "docs/intro/components.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Getting_Started"
        name: "Getting_Started"
        file: "docs/gettingstarted/index.md"
        preview_path: "docs/gettingstarted/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Develop"
        name: "Develop"
        file: "docs/develop/index.md"
        preview_path: "docs/develop/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
        

      
